### PR TITLE
Utility functions for converting C arguments

### PR DESCRIPTION
**Pull request by piodul**
- Adds utility functions which should simplify converting arguments from C to arguments usable by Rust
- Marks all extern functions as unsafe so that less `unsafe` blocks are needed
- Modifies existing functions so that they use the new utility functions

### CODE REVIEW

**Comment by cvybhu** [comment]
Looks good, but I don't like using `ptr_to_opt_box` to free boxed values
Maybe something like `free_boxed`? It would be clearer what's going on

**Comment by cvybhu** [comment]
let's merge this before my PR, I will use those utility functions instead of my own

**Review by Lorak-mmk — APPROVED** [review]

**Comment by piodul** [comment]
> Looks good, but I don't like using `ptr_to_opt_box` to free boxed values Maybe something like `free_boxed`? It would be clearer what's going on

OK, will change.

**Comment by piodul** [comment]
@cvybhu done, changed `ptr_to_opt_box` into `free_boxed`

**Review by cvybhu — APPROVED** [review]

**Comment by cvybhu** [comment]
LGTM, let's merge

**Pull request merged**
