### PR TITLE
Initial support for binding values to statements (only int32)

### PR DESCRIPTION
**Pull request by constantfold**
First, switch to our fork of Rust Driver, as some `Clone` traits were missing for necessary types and this version supports serializing `CqlValue`.

Second, I unwrap `CassStatement` from `Arc`, as this data type doesn't need to be thread-safe. This unwrapping makes it also easier to mutate this structure.

Finally, I implemented basic version of binding values to statements. On each `CassStatement` a `Vec` of bound values is stored (initially it is `Unset`). Newly implemented `cass_statement_bind_int32` allows for changing those values. Finally `cass_session_execute` now uses those bound values.

### CODE REVIEW

**Comment by Lorak-mmk** [comment]
Do we really need this RWLock? CassStatement doesn't have to be thread-safe (only CassSession and CassFuture do).

**Comment by constantfold** [comment]
> Do we really need this RWLock? CassStatement doesn't have to be thread-safe (only CassSession and CassFuture do).

How would I achieve it in Rust? I couldn't find a way to modify the contents of `Arc` other way.

**Comment by piodul** [comment]
> > Do we really need this RWLock? CassStatement doesn't have to be thread-safe (only CassSession and CassFuture do).
> 
> How would I achieve it in Rust? I couldn't find a way to modify the contents of `Arc` other way.

First, you don't have to do `Box<Arc<CassStatement>>`. You can convert an `Arc<CassStatement>` directly to a pointer and convert it back by using `Arc::from_raw` and `Arc::to_raw`.

Second, if you don't need thread-safety of the `CassStatement`, you could just accept a `*mut CassStatement` and modify the contents.

**Comment by constantfold** [comment]
v2: Unwrapped `CassStatement` from both `Arc` and `RwLock`.

**Review by Lorak-mmk — APPROVED** [review]

**Review by havaker — APPROVED** [review]

**Pull request merged**
