### PR TITLE
include: remove scylla-rust-wrapper/extern/cassandra.h

### LINKED ISSUE #116: Avoid redundant cassandra.h file
Currently, for building purposes, there is a duplicated `cassandra.h` file. Perhaps, it is possible to use symlinks to have a single file.

### PR DESCRIPTION
**Pull request by muzarski**
Fix: https://github.com/scylladb/cpp-rust-driver/issues/116

I updated `build.rs` so it now uses original `include/cassandra.h` file to generate bindings.
Thanks to that, we can remove the needless `scylla-rust-wrapper/extern/cassandra.h` file.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~[ ] I have implemented Rust unit tests for the features/changes introduced.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.~

### CODE REVIEW

**Comment by Lorak-mmk** [comment]
Could you, as part of this PR, find out why there need to be 2 of those files, and describe it in the comment somewhere?

**Comment by muzarski** [comment]
> Could you, as part of this PR, find out why there need to be 2 of those files, and describe it in the comment somewhere?

Time to dig into the depths of Cmake files. Wish me luck.

**Comment by muzarski** [comment]
> Could you, as part of this PR, find out why there need to be 2 of those files, and describe it in the comment somewhere?

So it just looks like `build.rs` makes use of `scylla-rust-wrapper/extern/cassandra.h` to generate bindings. But as I tested locally, removing `scylla-rust-wrapper/extern/cassandra.h`, and using `../include/cassandra.h` in `build.rs` works as well. 

So we can either retain a symlink in `extern/cassandra.h` or remove it and adjust the paths in `build.rs` to point to the original file. WDYT?

**Comment by Lorak-mmk** [comment]
I think it's fine to modify build.rs

**Comment by muzarski** [comment]
> I think it's fine to modify build.rs

Done. Updated the description and title accordingly.

**Review by Lorak-mmk — APPROVED** [review]

**Review by wprzytula — APPROVED** [review]

**Pull request merged**
