### PR TITLE
Add *_by_name and *_by_name_n variants of statement bind functions

### PR DESCRIPTION
**Pull request by constantfold**
Add *_by_name and *_by_name_n variants of statement bind functions, which work for prepared statements and allow to set a value based on the column name. 

Fix cass_prepared_bind to correctly initialize bound_values based on the received metadata. 

Small refactoring around CassCollection to CqlValue conversion.

### CODE REVIEW

**Comment by constantfold** [comment]
On the second look, it probably would be nicer using Rust macros rather than copy-pasta.

**Comment by piodul** [comment]
I agree that using macros for reducing boilerplate would be desirable here. I can try doing that.

**Comment by piodul** [comment]
Pushed an updated version with reduced boilerplate via macros

**Comment by piodul** [comment]
@avelanarius @Lorak-mmk please review

**Review by Lorak-mmk — APPROVED** [review]

**Pull request merged**
