### PR TITLE
ser: use rust-driver's builtin serialization for simple types

### PR DESCRIPTION
**Pull request by muzarski**
Previously, we would reimplement a serialization logic. It was a copy from rust driver, with the typechecks excluded.

In this PR, we get rid of the repeated code. To skip the typechecks (or rather, to make the typechecks always pass), we simply provide a valid ColumnType to SerializeValue::serialize().

This is a kind of hack, but thanks to that we don't have to reimplement serialization logic.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~[ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.~

### CODE REVIEW

**Review by wprzytula — APPROVED** [review]

**Review by Lorak-mmk — APPROVED** [review]
Isn't it possible to remove CassCqlValue entirely?

**Comment by muzarski** [comment]
> Isn't it possible to remove CassCqlValue entirely?

I think it is possible. The main obstacle are udts, collections and tuples. We would need to construct a valid `ColumnType` for each of these, and a nested `ColumnType` may be expensive to construct (some allocations). I think that there is no other way to use a builtin rust-driver's serialization with typechecks skipped for these types.

**Comment by Lorak-mmk** [comment]
Ok, let's keep the approach from this PR

**Comment by muzarski** [comment]
Actually, I think we could simply have a wrapper over `CqlValue`.

**Comment by muzarski** [comment]
> Actually, I think we could simply have a wrapper over `CqlValue`.

Give me a second, I'll investigate it and update this PR in case it's possible.

**Comment by muzarski** [comment]
Nvm, I don't think there is much sense to introduce a wrapper over CqlValue, since we would need to match variants that can never be created via cpp-rust-driver API (e.g. there is no way to create a `CqlValue::Counter()` value).

I think that we can merge it as is.

**Pull request merged**
